version: "3"
services:
    app:
        container_name: "jacc"
        build:
            context: ./
            dockerfile: dev.dockerfile
        volumes:
            - ./:/jacc
        ports:
            - 3000:3000
